// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc7bSDdLh_gTl8pJoxK3R3eRd0J7Q517E',
    appId: '1:566031276304:web:a35a7f809a3207b680ad95',
    messagingSenderId: '566031276304',
    projectId: 'mad5-bb404',
    authDomain: 'mad5-bb404.firebaseapp.com',
    storageBucket: 'mad5-bb404.appspot.com',
    measurementId: 'G-Y4NLRBFK94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFikHAbtiSYkZm8DCgzDuomTkwAopkRsg',
    appId: '1:566031276304:android:bf68a5115ee3799680ad95',
    messagingSenderId: '566031276304',
    projectId: 'mad5-bb404',
    storageBucket: 'mad5-bb404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk9pL7f9XuGFZyiEoFuvP430RtYsapG1c',
    appId: '1:566031276304:ios:4b89564dd7f7998680ad95',
    messagingSenderId: '566031276304',
    projectId: 'mad5-bb404',
    storageBucket: 'mad5-bb404.appspot.com',
    androidClientId: '566031276304-7g3asj6q63olq653r2cr96nrmh1arech.apps.googleusercontent.com',
    iosClientId: '566031276304-886nt4kiv3uh9od11bp9rikv76di16sf.apps.googleusercontent.com',
    iosBundleId: 'com.wesimplex.simplexconference',
  );
}
