name: simplex_conference_redo_repo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+13

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.3
  firebase_messaging: ^15.2.3
  firebase_crashlytics: ^4.3.3
  cloud_firestore: ^5.6.4
  cloud_functions: ^5.3.3
  google_sign_in: ^6.2.1
  flutter_native_splash: ^2.4.0
  cached_network_image: ^3.3.1
  file_picker: ^9.0.0
  auto_size_text: 3.0.0
  font_awesome_flutter: ^10.4.0
  intl: 0.19.0
  json_path: ^0.7.1
  page_transition: ^2.0.9
  url_launcher: ^6.2.6
  fluttertoast: ^8.2.12
  timeago: ^3.6.1
  photo_view: ^0.15.0
  material_symbols_icons: ^4.2668.0
  salomon_bottom_bar: ^3.3.2
  http: ^1.2.1
  flutter_excel: ^1.0.1
  share_plus: ^10.1.4
  add_2_calendar: ^3.0.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  map_location_picker: ^1.3.0
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  flutter_app_badge_control: ^0.0.2
  sign_in_with_apple: ^6.1.4
  flutter_keyboard_visibility: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/android12icon.png"
  image_path: "assets/images/appicon.png"
  min_sdk_android: 19
  web:
    generate: true
    image_path: "assets/images/webimage.png"
  windows:
    generate: false
  macos:
    generate: false



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/RedHatDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedHatDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/RedHatDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RedHatDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/RedHatDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/RedHatDisplay-BlackItalic.ttf
          weight: 900
          style: italic
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/DMSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/DMSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/DMSans-Black.ttf
          weight: 900
        - asset: assets/fonts/DMSans-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/images/
    - shorebird.yaml